name: 'Test Report'
on:
  workflow_run:
    workflows: ['.NET']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: test-report                  # Name of the check run which will be created
<<<<<<< HEAD
        path: 'Homework*/Hw*.Tests/TestResults/*.trx'                     # Path to test results (inside artifact .zip)
=======
        path: 'Homework*/Hw*Tests/TestResults/*.trx'                     # Path to test results (inside artifact .zip)
>>>>>>> master
        reporter: dotnet-trx              # Format of test results
